name: Automatic do login to matchwatch everyday

on:
  # push # (test)
  schedule:
    - cron: "0 21 * * *" # Runs At 21:00 UTC = 04:00 GMT+8 everyday

jobs:
  setup-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your dependencies

  login-to-matchwatch:
    needs: setup-and-verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script (login to matchwatch)
        env:
          APP: ${{ github.event.repository.name }}
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python3 matchwatch/main.py

  manutd-match-result:
    needs: setup-and-verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script (manutd match result)
        env:
          APP: ${{ github.event.repository.name }}
          MANUTD_APIKEY: ${{ secrets.MANUTD_APIKEY }}
        run: python3 manutd/main.py
