name: Automatic daily automation

on:
  schedule:
    - cron: "0 23 * * *" # 23:00 UTC (07:00 GMT+8)

# 👇 Global environment variables (shared across all jobs)
env:
  APP: ${{ github.event.repository.name }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set-python.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ./telegram ./logger

  manutd-match-result:
    needs: setup
    runs-on: ubuntu-latest
    env:
      MANUTD_APIKEY: ${{ secrets.MANUTD_APIKEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ./telegram ./logger
      - name: Run ManUtd script
        run: python manutd/main.py

  matchwatch:
    needs: setup
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ./telegram ./logger
      - name: Run Matchwatch script
        run: python matchwatch/main.py

  shipment-tracking:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NOTION_DAILY_TASK_TOKEN: ${{ secrets.NOTION_DAILY_TASK_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ./telegram ./logger
      - name: Run Shipment Tracking
        run: python shipment_tracking/main.py
